# Generated by Django 4.1.7 on 2023-02-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oiltype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='viscosity',
            name='oiltype',
        ),
    ]
