# Generated by Django 4.1.7 on 2023-02-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_created_alter_product_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.transmission'),
        ),
    ]
