# Generated by Django 4.1.7 on 2023-02-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_oiltype_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oiltype',
            name='category',
        ),
    ]
