# Generated by Django 4.1.7 on 2023-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_oiltype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='compounds',
            field=models.ManyToManyField(to='shop.compound'),
        ),
        migrations.AddField(
            model_name='category',
            name='fuels',
            field=models.ManyToManyField(to='shop.fuel'),
        ),
        migrations.AddField(
            model_name='category',
            name='oiltypes',
            field=models.ManyToManyField(to='shop.oiltype'),
        ),
        migrations.AddField(
            model_name='category',
            name='transmissions',
            field=models.ManyToManyField(to='shop.transmission'),
        ),
        migrations.AddField(
            model_name='category',
            name='viscosities',
            field=models.ManyToManyField(to='shop.viscosity'),
        ),
        migrations.AddField(
            model_name='category',
            name='vehicle_types',
            field=models.ManyToManyField(to='shop.vehicletype'),
        ),
    ]
