# Generated by Django 4.1.7 on 2023-02-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_filter_alter_category_compounds_alter_category_fuels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='compounds',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fuels',
        ),
        migrations.RemoveField(
            model_name='category',
            name='oiltypes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='transmissions',
        ),
        migrations.RemoveField(
            model_name='category',
            name='vehicle_types',
        ),
        migrations.RemoveField(
            model_name='category',
            name='viscosities',
        ),
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='shop.filter'),
        ),
    ]
