# Generated by Django 4.1.7 on 2023-02-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_compounds_remove_category_fuels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oiltype',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.filter'),
        ),
    ]
