# Generated by Django 4.1.7 on 2023-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_oiltype_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='oiltype',
            name='filter',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
