# Generated by Django 4.1.7 on 2023-02-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_category_filters_remove_oiltype_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.vehicletype'),
        ),
    ]
