# Generated by Django 4.1.7 on 2023-02-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_filter_compound_filter_fuel_filter_oiltype_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='oiltype',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='viscosity',
            name='filter',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
