# Generated by Django 4.1.7 on 2023-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_compound_filter_remove_fuel_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='compound',
            field=models.ManyToManyField(blank=True, to='shop.compound'),
        ),
        migrations.AddField(
            model_name='category',
            name='fuel',
            field=models.ManyToManyField(blank=True, to='shop.fuel'),
        ),
        migrations.AddField(
            model_name='category',
            name='oiltype',
            field=models.ManyToManyField(blank=True, to='shop.oiltype'),
        ),
        migrations.AddField(
            model_name='category',
            name='transmission',
            field=models.ManyToManyField(blank=True, to='shop.transmission'),
        ),
        migrations.AddField(
            model_name='category',
            name='vehicle_type',
            field=models.ManyToManyField(blank=True, to='shop.vehicletype'),
        ),
        migrations.AddField(
            model_name='category',
            name='viscosity',
            field=models.ManyToManyField(blank=True, to='shop.viscosity'),
        ),
    ]
